### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
Adds a German translation 👍

### CODE REVIEW

**Comment by NinjaCheetah** [comment]
Two quick questions:

1. Does translating the little "v" used in between the Title ID and version to "=" mean something?
2. I noticed that the hint text "Version" for the version text entry field isn't translated, and there's no note on it. Is that intentional? I thought it could be, but you left notes on all of the other things that weren't changed for the translation so I wasn't sure.

Other than that, looks good! Thanks for the translations!

**Comment by yeah-its-gloria** [comment]
`=` seems to just insert the original text as translation, since some words aren't different (e.g Version is the same in German and English)

**Comment by NinjaCheetah** [comment]
Ah okay, that makes sense. In that case, LGTM! Thanks again!

**Comment by NinjaCheetah** [comment]
No worries!

**Comment by NinjaCheetah** [comment]
@yeah-its-gloria Hey, just wanted to ask if you'd be willing to update your translations. I've finalized string changes for v1.3.0, so it'll be ready for release once all of the existing translations are up to date. Thanks!

**Comment by yeah-its-gloria** [comment]
for sure, I'll get onto that in a few days

**Comment by NinjaCheetah** [comment]
Sounds good, thank you!

**Pull request merged**
