### PR TITLE
Create nusget_ko.ts

### PR DESCRIPTION
**Pull request by DDinghoya**
Sorry, I couldn't specify a translation label item. TT

### CODE REVIEW

**Comment by NinjaCheetah** [comment]
Translations look good! Thank you!

For the future though, please try to keep all of your changes to one pull request and update that rather than opening multiple.

**Comment by NinjaCheetah** [comment]
@DDinghoya Hey, just wanted to ask if you'd be willing to update your translations. I've finalized string changes for v1.3.0, so it'll be ready for release once all of the existing translations are up to date. Thanks!

**Comment by DDinghoya** [comment]
> @DDinghoya Hey, just wanted to ask if you'd be willing to update your translations. I've finalized string changes for v1.3.0, so it'll be ready for release once all of the existing translations are up to date. Thanks!

Ok, I will work it after leaving the office today. :)

**Comment by NinjaCheetah** [comment]
Sounds good, thank you!

**Pull request merged**
